# Generated by Django 5.0.14 on 2026-09-15 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(help_text='Где необходимо выполнять привычку', max_length=255, verbose_name='Место выполнения')),
                ('time', models.TimeField(help_text='Когда необходимо выполнять привычку', verbose_name='Время выполнения')),
                ('action', models.CharField(help_text='Что представляет собой привычка', max_length=255, verbose_name='Действие')),
                ('is_pleasant', models.BooleanField(default=False, help_text='Поставьте галочку, если это приятная привычка-вознаграждение', verbose_name='Признак приятной привычки')),
                ('periodicity', models.PositiveIntegerField(default=1, help_text='Как часто выполнять привычку (например: 1 — каждый день, 7 — раз в неделю)', verbose_name='Периодичность (в днях)')),
                ('reward', models.CharField(blank=True, help_text='Чем пользователь себя вознаградит после выполнения', max_length=255, null=True, verbose_name='Вознаграждение')),
                ('duration', models.PositiveIntegerField(default=60, help_text='Сколько времени займет выполнение привычки (не более 120 секунд)', verbose_name='Время на выполнение (в секундах)')),
                ('is_public', models.BooleanField(default=False, help_text='Видна ли эта привычка другим пользователям в общем списке', verbose_name='Признак публичности')),
                ('related_habit', models.ForeignKey(blank=True, help_text='Приятная привычка, которая связана с полезной привычкой', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='useful_habits', to='habits.habit', verbose_name='Связанная привычка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL, verbose_name='Создатель привычки')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
                'ordering': ['id'],
            },
        ),
    ]
